### ISSUE TITLE
Weird spacing and animation when sending message

### ISSUE THREAD

**Issue by philippeauriach** [GetStream/react-native-samples#12] opened 2022-01-27 17:14 UTC
Hi,

I'm having trouble integrating GetStream inside a new project. The animation when sending a message is weird, it looks like all messages get down before getting up again (see attached screen recording).

It occurs in my project but also in the "iMessage clone example" project, freshly cloned to reproduce. It happens on iPhones, both with and without bottom safe insets (I thought it may come from the "safe area inset" but it appears not).

The screen recording is on an iOS simulator, iPhone 7, iOS 13.7, running the iMessage clone example

https://user-images.githubusercontent.com/920265/151409122-a891f106-4530-4354-956d-bb308d68c341.mov

thanks

EDIT: this does not occur when setting the property `enableMessageGroupingByUser={false}`. I guess hiding the previous "last status" while showing the new message causes this weird effect ?

EDIT2 : The issue is a bit less visible when replacing "30" by "8" here: https://github.com/GetStream/stream-chat-react-native/blob/538834396eabac02d843e5900f547180dd081726/package/src/components/Message/MessageSimple/MessageSimple.tsx#L102 . 

I guess an idea would be to have an animation on the last message bottom space, so when it goes from "last message" to "last before last message", it does not "jump" from 30 to 8 by slides beautifully

**Comment by vanGalilea** [comment] 2022-06-03 13:57
@philippeauriach, thanks for reaching out; duplicate of this [issue](https://github.com/GetStream/stream-chat-react-native/issues/1343)

I'll be closing this ticket, but feel free to contact us if you have any questions.

**Closed by vanGalilea** 2022-06-03 13:57 UTC

**Comment by philippeauriach** [comment] 2022-06-03 14:14
Hello @vanGalilea , duplicate ok, but the other one got closed ? Is this something that won't get fixed ?

thanks
